title:  Hire Niko E. U.

header_pages:
  - index.md
  - writing.md
  - learnmore.md

plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
minima:
  skin: dark

defaults:
  #blog posts
  - scope:
      path: "_posts/"
      type: posts
    values:
      permalink: blog/:year/:month/:day/:title